using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Assignment04
{
    public partial class SelectForm : Form
    {
        /// <summary>
        /// Program: Dollar Computers Assignment 3
        /// Name: Justin Schieck
        /// StudentID: 200328630
        /// App Creation Date: April 4th, 2017
        /// App Desc: Computer OrderForm 
        /// </summary>


        //public variables
        public StartForm PreviousForm;
        //private variables
        private product product;
        private ProductsContext DBO = new ProductsContext();

        public SelectForm()
        {
            InitializeComponent();
        }

        private void _NextButton_Click(object sender, EventArgs e)
        {

            ProductInfoForm productForm = new ProductInfoForm();
            productForm.Show();
            this.Hide();
        }

        private void _CancelButton_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }

        private void _SelectForm_Load(object sender, EventArgs e)
        {
            //Auto Generated by the database setup
            this.productsTableAdapter.Fill(this.dollarComputersDataSet.products);
            _CostConversion();

        }

        private void _CostConversion()
        {

            
            //makes a list with the products in dbo.products
            List<product> ProductList = (from product in DBO.products select product).ToList();
            CompDataGridView.DataSource = ProductList;

            //function for rounding
            foreach (product products in ProductList)
            {
                Decimal cost = (Decimal)products.cost;
                //rounds to 2 decimal places for cost column
                products.cost = Decimal.Round(cost, 2);
            }
        }

        private void _CompDataGridView_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (CompDataGridView.SelectedRows.Count > 0) // Checking to see if any cell is selected
            {

               ChoiceTextBox.Text = "Manufactuer: " + CompDataGridView.SelectedRows[0].Cells[2].Value.ToString() + ", Model: " + CompDataGridView.SelectedRows[0].Cells[3].Value.ToString()
              + ", Price: $ " + CompDataGridView.SelectedRows[0].Cells[1].Value.ToString();

                var itemSelected = (sender as DataGridView).SelectedRows[0];
                product Chosen = (product)itemSelected.DataBoundItem;
                //Sends chosen info to the product class
                Program.ChosenProduct = Chosen;

            }

            NextButton.Enabled = true;
        }


    }
}